apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgresql
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.auth.password }}"
  POSTGRES_USER: "{{ .Values.auth.username }}"
  POSTGRES_DB: "{{ .Values.auth.database }}"