apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: infra
type: Opaque
data:
  redis-password: {{ required "auth.password must be set via Terraform set_sensitive" .Values.auth.password | b64enc }}