apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: infra
  labels:
    app: redis
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redis
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      nodePort: {{ .Values.service.nodePort }}