apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
        - name: install-plugins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/sh
            - -c
            - |
              echo "[INFO] Installing Jenkins plugins into /var/jenkins_home/plugins ..."
              mkdir -p /var/jenkins_home/plugins
              jenkins-plugin-cli --plugin-download-directory /var/jenkins_home/plugins \
                --plugins \
                git \
                workflow-aggregator \
                pipeline-model-definition \
                pipeline-stage-view \
                blueocean \
                credentials-binding \
                docker-workflow \
                timestamper \
                job-dsl
              echo "[DONE] Plugins installed."
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JENKINS_ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: admin-user
            - name: JENKINS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: admin-password
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      volumes:
        - name: jenkins-home
          emptyDir: {}