apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  labels:
    app: jenkins
type: Opaque
stringData:
  admin-user: {{ .Values.auth.adminUser }}
  admin-password: {{ .Values.auth.adminPassword }}