apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  labels:
    app: jenkins
type: Opaque
stringData:
  jenkins-admin-user: {{ required "controller.adminUser must be set via Terraform" .Values.controller.adminUser | quote }}
  jenkins-admin-password: {{ required "controller.adminPassword must be set via Terraform" .Values.controller.adminPassword | quote }}