image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

auth:
  username: postgres   
  password: ""           
  database: appdb        

service:
  type: NodePort
  port: 5432
  nodePort: 30432

persistence:
  storageClass: local-path
  size: 5Gi

backup:
  schedule: "0 0 * * *"   # For tests change value to "*/5 * * * *" 
  retentionDays: 7
  path: /var/lib/postgresql/data/backups  