image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

auth:
  username: postgres   
  password: ""           
  database: appdb        

service:
  type: NodePort
  port: 5432
  nodePort: 30432

persistence:
  storageClass: local-path
  size: 5Gi

backup:
  schedule: "*/5 * * * *"   # Taking backup every 5 minutes now. For case, change value to "0 2 * * *"
  retentionDays: 7
  path: /var/lib/postgresql/data/backups  