# Installs and configures K3s worker nodes, connecting them to master
resource "null_resource" "k3s_worker_install" {
  for_each = { for i, w in var.workers : i => w }

  triggers = {
    worker_ip   = each.value.ip
    ssh_user    = each.value.ssh_user
    private_key = each.value.private_key
    master_ip   = var.master.ip
  }

  connection {
    host        = each.value.ip
    user        = each.value.ssh_user
    private_key = file(each.value.private_key)
  }

  # Upload Ubuntu preparation script
  provisioner "file" {
    source      = "${path.module}/scripts/prepare_ubuntu.sh"
    destination = "/tmp/prepare_ubuntu.sh"
  }

  # Upload worker installation script
  provisioner "file" {
    source      = "${path.module}/scripts/install_k3s_worker.sh"
    destination = "/tmp/install_k3s_worker.sh"
  }

  # Upload node token file (generated by master)
  provisioner "file" {
    source      = local.node_token
    destination = "/tmp/node-token"
  }

  # Execute scripts remotely on worker node
  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/prepare_ubuntu.sh /tmp/install_k3s_worker.sh",
      "sudo /tmp/prepare_ubuntu.sh",
      "sudo /tmp/install_k3s_worker.sh 'https://${var.master.ip}:6443' '/tmp/node-token'"
    ]
  }

  depends_on = [null_resource.k3s_master_read_node_token]
}